name: Deploy Spring Boot App to EC2 (Ubuntu)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

        - name: Show commit SHA
          run: echo "Current Commit SHA: $GITHUB_SHA"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar

      - name: Check built JAR content (확인용)
        run: |
          ls -lh build/libs/
          jar tf build/libs/app.jar | grep application-local.properties || echo "❌ application-local.properties 누락됨"
      - name: Upload JAR to EC2
        run: |
          scp -i ~/.ssh/id_rsa build/libs/app.jar \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/app.jar
      - name: Restart App on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pkill -f 'app.jar' || true
            nohup java -jar /home/${{ secrets.EC2_USER }}/app/app.jar --spring.profiles.active=local > /home/${{ secrets.EC2_USER }}/app/app.log 2>&1 &
          EOF
