server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://guardion.cvsguqoo21it.ap-southeast-2.rds.amazonaws.com:3306/guardion?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: ehdusrla
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.guardion: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: "yoursecretkeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

mqtt:
  broker: tcp://localhost:1883 #tcp://ec2-3-39-253-151.ap-northeast-2.compute.amazonaws.com:1883
  client-id: guardion-sub #서버가 test/topic을 구독하면서 메시지를 받을 때 guardion-sub이라는 ID로 연결함.
  sub-topic: test/topic
  publisher-id: guardion-pub #서버가 특정 topic으로 메시지를 publish할 때, guardion-pub이라는 ID로 연결함.

cors:
  allowed-origin : http://localhost:3000

# application.yml
#springdoc:
#  swagger-ui:
#    url: /v3/api-docs
#    disable-swagger-default-url: true
#    config-url: /v3/api-docs/swagger-config

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # 정렬기준
    tags-sorter: alpha # 태그정렬기준
    path: /swagger
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
