server:
  address: 0.0.0.0
  port: 8080 #..
spring:
  datasource:
    url: jdbc:mysql://guardion.cvsguqoo21it.ap-southeast-2.rds.amazonaws.com:3306/guardion?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: ehdusrla
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.guardion: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: yoursecretkeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

mqtt:
  broker: tcp://ec2-3-39-253-151.ap-northeast-2.compute.amazonaws.com:1883 #tcp://localhost:1883
  client-id: guardion-sub-l #guardion-sub
  sub-topic: test/topic/l #테스트용 구독 토픽
  publisher-id: guardion-pub-l #guardion-pub

cors:
  allowed-origin : http://localhost:3000

# application.yml
#springdoc:
#  swagger-ui:
#    url: /v3/api-docs
#    disable-swagger-default-url: true
#    config-url: /v3/api-docs/swagger-config

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # 정렬기준
    tags-sorter: alpha # 태그정렬기준
    path: /swagger
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match: #..

mail:
  from: "guardionapp@gmail.com"     # 발신 주소(SMTP에서 허용된 주소여야 함)
  reset-base-url: "https://your-frontend/reset-password"  # 토큰이 붙는 프론트엔드 링크

app:
  reset-token:
    ttl-minutes: 20  # 토큰 유효기간 (분 단위)
