server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: dkim
    password: ehdusWkd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.guardion: DEBUG

jwt:
  secret: "yoursecretkeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

mqtt:
  broker: tcp://localhost:1883
  client-id: mqtt-client
  topic: your/topic
