CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "salt" varchar NOT NULL,
  "organization" varchar,
  "institution" varchar,
  "role" varchar NOT NULL,
  "last_login_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "device_status" (
  "id" SERIAL PRIMARY KEY,
  "device_id" INTEGER NOT NULL,
  "internal_temperature" FLOAT,
  "internal_humidity" FLOAT,
  "device_gps_id" INTEGER UNIQUE,  -- 일대일 관계 강제로, 여러 값을 가질 수 있다면 UNIQUE 제거 필요
  "cover_status" BOOLEAN,
  "battery_exist" BOOLEAN,
  "beep_status" BOOLEAN,
  "light_status" BOOLEAN,
  "last_updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "device" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "serial_number" TEXT,
  "device_name" TEXT,
  "device_status_id" INTEGER UNIQUE,
  "temperature_setting" INTEGER,
  "beep_setting" INTEGER,
  "light_setting" INTEGER,
  "is_connected" BOOLEAN,
  "last_updated" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "device_gps_log" (
  "id" SERIAL PRIMARY KEY,
  "latitude" FLOAT,
  "longitude" FLOAT,
  "device_status_id" INTEGER NOT NULL,
  "recorded_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/* -- 선택적으로 남기기
CREATE TABLE "device_gps_log_2" (
  "id" SERIAL PRIMARY KEY,
  "latitude" FLOAT,
  "longitude" FLOAT,
  "device_status_id" INTEGER NOT NULL,
  "recorded_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
*/

CREATE TABLE "device_data" (
  "id" SERIAL PRIMARY KEY,
  "device_id" INTEGER NOT NULL,
  "internal_temperature" FLOAT,
  "internal_humidity" FLOAT,
  "device_gps_id" INTEGER UNIQUE,
  "cover_status" BOOLEAN,
  "battery_exist" BOOLEAN,
  "beep_status" BOOLEAN,
  "light_status" BOOLEAN,
  "recorded_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "alert" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "type" TEXT,
  "device_status_id" INTEGER UNIQUE NOT NULL,
  "message" TEXT,
  "severity" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "is_read" BOOLEAN,
  "is_resolved" BOOLEAN
);

CREATE TABLE "user_activity_log" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "activity_type" TEXT,
  "activity_target" TEXT,
  "activity_detail" TEXT,
  "ip_address" inet,
  "user_agent" TEXT,
  "created_at" TIMESTAMP
);

COMMENT ON COLUMN "user_activity_log"."id" IS '기본 키, 자동 증가';

-- 🔗 Foreign Keys

ALTER TABLE "device" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "device" ADD FOREIGN KEY ("device_status_id") REFERENCES "device_status" ("id");

ALTER TABLE "device_data" ADD FOREIGN KEY ("device_id") REFERENCES "device" ("id");
ALTER TABLE "device_data" ADD FOREIGN KEY ("device_gps_id") REFERENCES "device_gps_log" ("id");

ALTER TABLE "device_status" ADD FOREIGN KEY ("device_id") REFERENCES "device" ("id");
ALTER TABLE "device_status" ADD FOREIGN KEY ("device_gps_id") REFERENCES "device_gps_log" ("id");

ALTER TABLE "alert" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "alert" ADD FOREIGN KEY ("device_status_id") REFERENCES "device_status" ("id");

ALTER TABLE "device_gps_log" ADD FOREIGN KEY ("device_status_id") REFERENCES "device_status" ("id");
-- ALTER TABLE "device_gps_log_2" ADD FOREIGN KEY ("device_status_id") REFERENCES "device_status" ("id");

ALTER TABLE "user_activity_log" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
