CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "organization_name" varchar,
  "institution_name" varchar,
  "role" varchar NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- BaseEntity에서 상속
);

CREATE TABLE "device_data" (
  "id" SERIAL PRIMARY KEY,
  "device_id" INTEGER NOT NULL,
  "internal_temperature" FLOAT,
  "internal_humidity" FLOAT,
  "device_gps_id" INTEGER UNIQUE,  -- 일대일 관계 강제로, 여러 값을 가질 수 있다면 UNIQUE 제거 필요
  "door_status" BOOLEAN,
  "battery_exists" BOOLEAN,
  "beep_status" BOOLEAN,
  "light_status" BOOLEAN,
  "last_updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- BaseEntity에서 상속
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- BaseEntity에서 상속
);

CREATE TABLE "device" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "serial_number" TEXT UNIQUE,  -- UNIQUE 제약 추가
  "device_name" TEXT,
  "temperature_setting" INTEGER,
  "beep_setting" INTEGER,
  "light_setting" INTEGER,
  "is_connected" BOOLEAN,
  "data_last_recorded at" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "device_gps_log" (
  "id" SERIAL PRIMARY KEY,
  "latitude" FLOAT,
  "longitude" FLOAT,
  "device_status_id" INTEGER NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "alert" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "device_id" INTEGER NOT NULL,
  "alert_code" VARCHAR,
  "alert_type" VARCHAR,  -- ENUM으로 저장
  "device_data_id" INTEGER,
  "message" TEXT,
  "alert_severity" VARCHAR,  -- ENUM으로 저장
  "is_read" BOOLEAN,
  "is_resolved" BOOLEAN,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "user_activity_log" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "activity_type" VARCHAR,  -- ENUM으로 저장
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COMMENT ON COLUMN "user_activity_log"."id" IS '기본 키, 자동 증가';

-- 🔗 Foreign Keys 제약 조건

ALTER TABLE "device" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "device_data" ADD FOREIGN KEY ("device_id") REFERENCES "device" ("id");
ALTER TABLE "device_data" ADD FOREIGN KEY ("device_gps_id") REFERENCES "device_gps_log" ("id");
ALTER TABLE "alert" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "alert" ADD FOREIGN KEY ("device_id") REFERENCES "device" ("id");
ALTER TABLE "alert" ADD FOREIGN KEY ("device_data_id") REFERENCES "device_data" ("id");
ALTER TABLE "user_activity_log" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
